### ISSUE TITLE
add option to use Silk Touch II for silking spawners

### ISSUE THREAD

**Issue by CaszGamerMD** [dnyferguson/MineableSpawners#12]
one of my favorite options in SilkSpawners was the option to use Silk Touch II for silking spawners so that way silk touch didnt feel like a very overpowered enchantment

**Comment by WhyDoWeWonder** [comment]
I support this, would love to have an option for silk touch level and/or an option for lore.

**Comment by ghost** [comment]
Thanks for the suggestion, I've added this in the latest update
