### ISSUE TITLE
Suggestion/question

### ISSUE THREAD

**Issue by Feglord** [dnyferguson/MineableSpawners#18]
Hi there!

I found your plugin when I was searching for something that would allow me to give and mine spawners for a server, and this one works exactly as intended and advertised.

My reason for making this post was to ask if I'm missing something and/or, if I am missing something, to add a feature to the plugin.

I was looking to see if it might be possible to allow players to only mine spawners that are given using your plugin and disallow players the ability to mine naturally generated spawners via permission.

If this isn't currently possible then fair enough, I can understand that it might be difficult to differentiate between both vanilla and spawned, however it would be nice to see something like this possibly added.

Another small suggestion I might make while I'm here is to ask if it might be possible to customize the names of the spawners when they are given, as some spawners come out with odd names compared to their mob coutnerpart (e.g. Mooshroom Spawners come through as mushroom_cow)

Thank you for your work on this plugin and keeping it up to date!
Cheers!

**Comment by ghost** [comment]
I made spawner names more configurable in the new update however I don't see myself adding a system that tracks which spawners are natural or not, maybe in the future who knows.
