### ISSUE TITLE
Spawners not mineable with Silk Touch higher than 1

### ISSUE THREAD

**Issue by s1h4d0w** [dnyferguson/MineableSpawners#19]
**Edit:** Apologies, I just saw the older issue and the option in config to require Silk Touch 2. So the title of this should rather be "Allow any level of Silk Touch". 

Maybe add a "required" level in the config that's just an integer, and if the level of the item is higher than the level in config just allow player to mine it? So I could set it to 1 and have any level of Silk Touch work for mining spawners.

---

**Original message:**
So we use a plugin that generates bosses in the wild and they drop items with higher than normal enchantments on them. 

Turns out they can drop pickaxes with Silk Touch 5. Not sure if that does anything, but players were not able to mine spawners with it while having all the required permissions. The plugin just tells them they need a pick with Silk Touch. I gave that player an iron pickaxe with Silk Touch 1 and it worked perfectly.

Could you make the plugin accept any level of Silk Touch?

**Comment by ghost** [comment]
Hi, a new update now allows you to set which silk touch level is required so that level and any greater level will work.
