### ISSUE TITLE
1.15 Support

### ISSUE THREAD

**Issue by WillFP** [dnyferguson/MineableSpawners#24]

**Comment by ghost** [comment]
Have you tried it on 1.15? what doesn't work?

**Comment by amnotbananaama** [comment]
Loaded up the plugin in 1.15.2 Spigot. Without any other plugins installed (including permissions plugins), MineableSpawners enables and works just fine. Handles spawners, and even the new 1.15 bees without a problem for me.

**Comment by ghost** [comment]
Yeah thats what I figured would happen, people been asking me to add 1.15 without even trying it. Thanks for debunking it.
