### ISSUE TITLE
Suggestion: Permission nodes for different % chances

### ISSUE THREAD

**Issue by MilesBHuff** [dnyferguson/MineableSpawners#25]
I'm the head admin of [SettleScape](https://github.com/SettleScape), and a common request from our players is that we make it so that every rank (group) has a different chance to silk-touch spawners.  Currently, it is not possible to do that with your plugin.  The traditional way to do this sort of thing, is to create permission nodes for different percent chances.  These permissions can then be doled out to the different ranks, giving each a different chance of successfully silk-touching spawners.

**Comment by wsman217** [comment]
Oh dang, I just went and suggested this on the spigot without ever reading this, I'm probably going to make a fork of this and the make a pr with this and if the owner likes it they can merge it and if they don't they can probably build off of my code or just completely disregard it.

**Comment by ghost** [comment]
Added in the newest update
