### ISSUE TITLE
Console Flooded with EntityType's

### ISSUE THREAD

**Issue by A248** [dnyferguson/MineableSpawners#29]
When MineableSpawners starts up it prints all the available mob types to the server console.

If every plugin did this the console output from server startup would be 20x longer.

This is quite annoying. Please either disable it or add an option to disable.

**Reference**
https://github.com/dnyferguson/MineableSpawners/blob/master/src/main/java/com/dnyferguson/mineablespawners/MineableSpawners.java#L43

**Comment by ghost** [comment]
This isnt a bug, its intended as usually I get a lot of requests about available mob types
