### ISSUE TITLE
Suggestion: Use Logger#info instead of System.out

### ISSUE THREAD

**Issue by A248** [dnyferguson/MineableSpawners#31]
System.out.println is all over the source code. While it does not affect anything, using `plugin.getLogger().info("message");` is cleaner and doesn't require you to remember to prepend "[MineableSpawners]" before every message – the logger does that for you.

Since MineableSpawners already uses dependency injection (hooray!) this refactor wouldn't be too hard. This will make MineableSpawners much more maintainable, helping you to improve it over time.

**Comment by ghost** [comment]
Thanks for the recommendation however I do not plan on doing this at the moment because System.out.println isn't used for much and is still maintainable
