### ISSUE TITLE
Spigot 1.8.8 bug

### ISSUE THREAD

**Issue by Jacielegit** [dnyferguson/MineableSpawners#33]
When typing a command the plugin always sends the same message in the chat and does nothing else. Prints: https://prnt.sc/s14cf0

**Comment by ghost** [comment]
I dont get that on 1.8 so I'll need more information

**Comment by Jacielegit** [comment]
Console don't show anything.
https://prnt.sc/s1912a

**Comment by Jacielegit** [comment]
i just have this message of the plugin, no more.

**Comment by ghost** [comment]
I don't see this being caused by this plugin, it looks like something might be cancelling the command. Not sure what to tell you, I can't do anything with what you've brought forward, sorry.
