### ISSUE TITLE
Fix for onEggChange negative permission

### ISSUE THREAD

**Issue by jakeau** [dnyferguson/MineableSpawners#35]
@EventHandler (ignoreCancelled = true)
    public void onEggChange(PlayerInteractEvent e) {
        if (!e.getAction().equals(Action.RIGHT_CLICK_BLOCK)) {
            return;
        }

        Player player = e.getPlayer();
        ItemStack itemInHand = e.getItem();

        if(!player.hasPermission("mineablespawners.changeegg"))
        	return;

If you get a chance please implement :)

**Comment by ghost** [comment]
This would not fix it, the plugin already does this check when require-permission is set to true in config. Also you use a different perm not documented anywhere.
