### ISSUE TITLE
Mob spawners not working as in vanilla mc

### ISSUE THREAD

**Issue by joeridukker** [dnyferguson/MineableSpawners#4]
First of, amazing plugin, love it.
I noticed my spawners do not work as they do in vanilla minecraft, My spawners used to spawn multiple mobs at the time, I dont really see this happening on my server. Also, mobs dont spawn in the air but need a solid block for them to spawn on. On my singeplayer 1.13 for example endermans can spawn in the air. Not sure if this is a spawner plugin issue or something else, Please help

**Comment by ghost** [comment]
Hey, this plugin literally only affects breaking and placing spawners, along with right clicking them with mob eggs. It should have no effect towards the spawning behavior, it should be vanilla. If you want you could send me a list of plugins and I could have a look to see if I see any possible culprits.
