### ISSUE TITLE
Plugin Fails to Enable on Spigot 1.16

### ISSUE THREAD

**Issue by amnotbananaama** [dnyferguson/MineableSpawners#44]
**Issue**
Attempting to use MineableSpawners on 1.16 Spigot (first build released [yesterday](https://www.spigotmc.org/threads/spigot-bungeecord-1-16-1.447405/)) results in the plugin failing to enable.

**Log**
https://pastebin.com/raw/C1FFA1Z6

**Analysis**
It looks like the MineableSpawners is unable to deal with newer or unexpected versions of Spigot than it was originally coded for. The naive fix would just be adding another `if` check for 1.16 [here](https://github.com/dnyferguson/MineableSpawners/blob/99951db539cb8a48afadf926f46668b18a4ed677/src/main/java/com/dnyferguson/mineablespawners/MineableSpawners.java#L105), but It would be great if the plugin could at least try to enable on newer versions of Minecraft, especially since as you've said this is a project you are working on in your spare time.

Thank you!

**Comment by Tacodiva** [comment]
#45 should fix this.

**Comment by amnotbananaama** [comment]
@ShiryuDev your PR is working great on 1.16.1 thank you!

**Comment by amnotbananaama** [comment]
Closing with https://github.com/dnyferguson/MineableSpawners/commit/2870bce88c0485431872140edaca658530c74677
