### ISSUE TITLE
Spawners cant be picked up/given to players (1.16.2)

### ISSUE THREAD

**Issue by ic22487** [dnyferguson/MineableSpawners#52]
https://pastebin.com/55Yfcdzd

i upgraded from an earlier version and still have the same permissions set up from last time

**Comment by ghost** [comment]
Cant reproduce, seems like the nbt api system it uses couldnt load support for your version but it works for me when trying 1.16.2 and 1.16.3. Maybe grab a fresh copy of the plugin and try that
