### ISSUE TITLE
Set Pickaxe type issue (Players may still mine with any pickaxe they'd like)

### ISSUE THREAD

**Issue by AZFire1** [dnyferguson/MineableSpawners#53]
**Issue:**
 * This issue is when you set the tools that are able to be used for mining in config to the specified ones you would like and then mine the spawners with a tool that is not in that list which are the ones you have set.

**Steps to reproduce:**
 * You need to set some pickaxe types, mine are gold, iron and netherite. 
 * After, you reload the plugin and then try to break it with a pickaxe that isn't in the list.
 * And, then notice it still goes in your inventory as if it was an allowed tool.

**My Config:**
 * https://paste.helpch.at/afisezosum.coffeescript

_-------------------------------------------------------------------------------------------------_

**Conclusion:**
I may have done the config wrong, let me know if I did.

**Comment by ghost** [comment]
Unable to reproduce what you claim however if you have 'still-break: true' like you do, if the player doesnt have the wrong tool (or doesnt meet one of the other requirements), it will simply break the spawner
