### ISSUE TITLE
Players are able to mine spawners in Towny claims

### ISSUE THREAD

**Issue by o7-hmoe** [dnyferguson/MineableSpawners#54]
As stated, players are able to mine spawners if they are in Towny claims. I talked to the Towny developers, and they said it is because the plugin is operating in the wrong priority. Here is a video showing the issue (not my video): https://www.youtube.com/watch?v=ixwC5ZASHfQ&feature=emb_logo&ab_channel=c6070

Please let me know if anything can be done about this.

Using the latest version of MineableSpawners, on Spigot 1.16.1

**Comment by ghost** [comment]
You can get someone to edit it and compile it with different event priorities until it works for you. No other user even reported protection plugin conflicts yet, in a future update I'll look into making it where you can set the priorities yourself in config but that will be whenever I have free time

**Comment by o7-hmoe** [comment]
I'll close this ticket on this comment: I was able to fix this issue by changing the plugin .jar to 'zMineableSpawners.jar' which put it at the bottom of the plugin list. Upon a reboot, the issue was fixed. No other changes were made.
