### ISSUE TITLE
Reset spawner (1.16.3)

### ISSUE THREAD

**Issue by aurel85** [dnyferguson/MineableSpawners#55]
Hi,

[QUOTE="sixamscrew, post: 3942626, member: 38711"]Hey, since updating to latest 3.0.8 for 1.16.2 server, whenever a player places old spawners (1.16.1), all of them turn to pig spawners. Do I have to regen the config? Thanks.[/QUOTE]

The same in 1.16.3 (I didn't have the problem in 1.16.2).
All transformed spawners dating from before 1.16.3 are reset to Pig... :/
I use Paper 1.16.3 and the last version of  this plugin.

My plugins : https://www.spigotmc.org/threads/mineablespawners-1-8-1-16-silkspawners-alternative.334866/page-14

**Comment by ghost** [comment]
I cant see this being an issue of my plugin. It works fine for me on 1.16.3 and if the conversion from an older version bugged them out I suspect this to be a spigot conversion issue or something. My plugin doesn't affect already placed spawners, once they are placed and changed they are out of my spawners hands and get handled by the server like any other spawner.
