### ISSUE TITLE
Fox display in spawner (1.14.2)

### ISSUE THREAD

**Issue by aurel85** [dnyferguson/MineableSpawners#7]
Hi,

I use PaperSpigot 1.14.2 and the last version of this plugin.

In 1.14.2 fox spawners don't display the fox inside the spawner. I tested all new mobs 1.14 is the only one with whom it does.

![2019-06-07_18 45 37](https://user-images.githubusercontent.com/24486147/59123943-ba7a0200-895e-11e9-91a8-fcfd4ba8f839.png)

**Comment by ghost** [comment]
Hi this is not a bug related to this plugin but rather just a 1.14.2 bug, I tested and the foxes still spawn and I don't touch how they're shown in the plugin, I just set the type of mob.

**Comment by aurel85** [comment]
Ok !
