### ISSUE TITLE
(Bug) Duplicate glitch found

### ISSUE THREAD

**Issue by DarkKingKaan** [dnyferguson/MineableSpawners#72]
Hello, I would like to report a duplicate glitch.

I have a Custom Enhants plugin (Advanced Enchantments), and one of the enchants called "Detonate" has the ability to break a large area of blocks. Some smart players have found a duplicate glitch using this enchant combined with SilkTouch. When breaking a block next to a spawner, the spawner would drop its item but will also stay in place, therefore duplicating itself. I have done some things to stop people from selling spawners for now, but this is a big issue.

This could also partially be an issue caused by AdvancedEnchantments but I'm just letting you know if you may be able to do something about it.

I use the latest Paper 1.16.5, running on Linux with Java 11, using the latest version of both mentioned plugins.

Thank you in advance for your answer.

**Comment by rhystedstone** [comment]
This would most likely be a problem with Advanced Enchantments, as MineableSpawners would check when you've broken a spawner. Check to see if Advanced Enchantments allows you to prevent blocks from breaking.

**Comment by ghost** [comment]
Its definitely an issue with advanced enchantments and I'm willing to bet it would work on other enchant plugins doing similar things unless they are explicitly supported by the silkspawners plugin or you use their build in silk spawners feature. I have no plans to support a bunch of random plugins so if you want that kind of support you will have to do it yourself/with a dev that'll edit this public code for you.

**Comment by DarkKingKaan** [comment]
It was indeed a problem on their side. I reported the issue to them too. They have now added an option to blacklist some items for this enchant and it has fixed my problem.
