### ISSUE TITLE
No issue just suggestion

### ISSUE THREAD

**Issue by Technologx** [dnyferguson/MineableSpawners#8]
Can you please add a feature to make certain mobs illegal. This will make it easier on server owners who don't want certain mobs to be able to be spawned with a spawner.

**Comment by xCykrix** [comment]
@dnyferguson if you are not actively working on this issue, I will integrate the typed permissions into mining spawners.

@Technologx you can use individual permissions to accomplish this for everything but breaking at this time.
`mineablespawners.spawner.<type>` /spawner
`mineablespawners.eggchange.<type>` egg changing
with `require-individual-permission` set to true for both.

**Comment by dnyferguson** [comment]
> @dnyferguson if you are not actively working on this issue, I will integrate the individual permissions into mining spawners.
> 
> @Technologx you can use individual permissions to accomplish this for everything but breaking at this time.
> `mineablespawners.spawner.<type>` /spawner
> `mineablespawners.eggchange.<type>` egg changing
> with `require-individual-permission` set to true for both.

Not sure what you are talking about? hes talking about preventing certain mobs from spawning, nothing about mining them

**Comment by xCykrix** [comment]
@dnyferguson 
You already have the ability to blacklist changing spawner types with permissions, however for the OP request you would likely want to make it configurable to never obtain blacklisted spawner types and cancel events for existing blacklisted spawners.
I would seriously doubt you would want a bunch of blacklisted spawners floating around if they are naturally obtainable?

**Comment by dnyferguson** [comment]
I see, that would probably be decent for those who need it, of course would do like for changing types where we can disable the permission check for those who don't need this. If you want to work on this and make a PR, I'm open to it, else I will get to it sometime. Thanks for the clarification

**Comment by dnyferguson** [comment]
Added individual permissions for spawner mining in the new update
