### ISSUE TITLE
Duply bug

### ISSUE THREAD

**Issue by Loubafritz** [dnyferguson/MineableSpawners#92]
Hello, when I break a spawner, there is the type of the ex cave spider spawner that goes in my inventory but there is also a normal (pig) spawner that goes in my inventory so it duplicates x2 the spawner

**Comment by itsfergydanny** [comment]
Sorry this project is unmaintained. This is not a bug with thi splugin in particular but most likely due to your usage of an area protection plugin that's not compatible with it
