### ISSUE TITLE
Add cooldown for spawners placing

### ISSUE THREAD

**Issue by piotrskibapl** [dnyferguson/MineableSpawners#94]
Hi there,

Players on my server found a way to quickly earn mob loots by placing a spawner, killing the spawned mobs (mobs are always spawning right after the mob spawner was placed), destroying the spawner, and placing it again. This way the amount of spawned mobs is significantly increased.

I have added a simple cooldown for mob spawner placing using Skript (if you break a spawner, you can place one only if at least a minute passed), however, I think that it could be useful if that was implemented into MineableSpawners. Another idea would be to block mob spawner spawns for a minute after the spawner was placed.

That's not a must-have for me as I already found a solution to this problem, but I'm leaving the suggestion for you. Thanks for the great work! :)

**Comment by itsfergydanny** [comment]
Hi, thanks for taking the time to make a suggestion, unfortunately this project has been unmaintained for a while and I will try to make that clearer so people don't waste their time.
