### ISSUE TITLE
The NBT-API located at 'package com.dnyferguson.mineablespawners.nbtapi' is outdated.

### ISSUE THREAD

**Issue by andrewkm** [dnyferguson/MineableSpawners#96]
```
[15:32:54] [Thread-53/WARN]: [NBTAPI] [NBTAPI] The NBT-API located at 'package com.dnyferguson.mineablespawners.nbtapi' seems to be outdated!
[15:32:54] [Thread-53/WARN]: [NBTAPI] [NBTAPI] Current Version: '2.10.0-SNAPSHOT' Newest Version: 2.10.0'
[15:32:54] [Thread-53/WARN]: [NBTAPI] [NBTAPI] Please update the NBTAPI or the plugin that contains the api(nag the mod author when the newest release has an old version, not the NBTAPI dev)!

```

**Comment by AverageFemale** [comment]
Have you tried updating MineableSpawners?

**Comment by andrewkm** [comment]
We are using the correct version, compiled against: https://github.com/itsfergydanny/MineableSpawners/commit/293f3aa7c129dd3c543c3c83704321e894f0df5d

**Comment by AverageFemale** [comment]
Oh I see the error now. I'll see if I can do anything about it.

**Comment by AverageFemale** [comment]
I've tried the plugin on a locally hosted server, and came up with no NBT API error.
Is this error still happening? It's been 15 days since your issue began. If so, try reinstalling it.
Is the plugin .jar named: `MineableSpawners-3.1.4.jar`? If not, try installing 3.1.4 on the plugin's spigot page.

**Comment by andrewkm** [comment]
It is a rare occurrence that this happens. About once every 4-5 days. But it does happen.

As well as previously stated we are running the latest version of the plugin built upon the commit above.

Yes that is the .jar name.

**Comment by electronicboy** [comment]
This would potentially be a happenchance with how maven is resolving the dependency and maybe pulling different versions? PL uses 2.10.0-SNAPSHOT, yet, 2.10.0 has been released, which is deemed as outdated to the version checker, so, at the very least, should probably bump to the release version

**Comment by AverageFemale** [comment]
> This would potentially be a happenchance with how maven is resolving the dependency and maybe pulling different versions? PL uses 2.10.0-SNAPSHOT, yet, 2.10.0 has been released, which is deemed as outdated to the version checker, so, at the very least, should probably bump to the release version

I've done that in my PR, I'ma also compile it just in case `itsfergydanny` doesn't ever respond to any of these.
Edit: Couldn't compile it, my laptop isn't strong enough lmao.

**Comment by andrewkm** [comment]
Reached out to danny.
Hopefully he should do it soon.

**Comment by itsfergydanny** [comment]
I'll look to update it but for future reference its a meaningless error and probably the only pain point of using this API in public plugins, it makes people freak out for nothing.

I always update the API when a new mc version comes out, which is pretty much the only time it needs to be updated unless something major needs fixing.
